### ISSUE TITLE
ボール/ボルトの関数をまとめる

### ISSUE THREAD

**Issue by Slimebreath6078** [Slimebreath6078/SBband#50]
ほぼ全部コピペなのでまとめる（ウォーターボールなど多少動作が違うものがあるが）

**Comment by Slimebreath6078** [comment]
クラス化しようか引数を追加してまとめようか悩んだけど、クラス化の方がいいかなこれ

**Comment by Hourier** [comment]
クラス化しつつ引数でまとめるのが良いですね！

**Comment by Slimebreath6078** [comment]
承知いたしました
引数追加した一つの関数にまとめるのではなくクラス化で行きます
