### ISSUE TITLE
モンスターの弱点、状態異常耐性、種族、徳、動作等のフラグをまとめる

### ISSUE THREAD

**Issue by Slimebreath6078** [Slimebreath6078/SBband#78]
Flags1やFlags2などにごっちゃにまとまってるので思い出のリファクタリングのために分ける

**Comment by Slimebreath6078** [comment]
またいくつか疑問点が出てきたので質問を

UNIQUE とNONLIVING はスレイ対象のenum class に含めてしまってよろしいでしょうか（ESPの処理などのコピペ低減がしやすくなります）

**Comment by Slimebreath6078** [comment]
承知いたしました。では引き続き進めていきます
私はMonsterAttrType にしておりましたが、ATTR_**** というフラグが既にあるのでKind の方が確かに良さそうなのでそちらにしようと思います

**Comment by Hourier** [comment]
よろしくお願いします
オーラの件は先ほどマージされたので、それなりにしっかりした内容になっているはずです
併せてご参考下さい

**Comment by Slimebreath6078** [comment]
現在グループとしてまとまっていないものは以下です
```
FORCE_DEPTH
FORCE_MAXHP

HAS_FRIENDS
ESCORT
MORE_ESCORT

CAN_SPEAK

RIDING

INVISIBLE
COLD_BLOOD
KAGE
TANUKI
ELDRITCH_HORROR

MULTIPLY

REGENERATE

POWERFUL
PREVENT_SUDDEN_MAGIC

CHAMELEON

REFLECTING
NO_FEAR
NO_STUN
NO_CONF
NO_SLEEP
```

**Comment by Slimebreath6078** [comment]
上記につきまして PREVENT_SUDDEN_MAGIC は動作の方に移動し、他は全て今しがた出したものにひとまとめにいたしました
